### ISSUE TITLE
[Mobile SDK] Identity Wallet - Create Identity

### ISSUE THREAD

**Issue by rauljareno** [iden3/polygonid-flutter-sdk#28]
create identity(seed phrase) - return auth сredential and id // from seed 
- [x] create key pair
- [x] save keys
- [x] create auth claim ( revocation nonce is hardcoded, no expiration date)
- [ ] CreateIdentityMerkleTrees(storage) 
- [ ] add auth claim to claims tree
- [ ] calculate state
- [x] calculate ID
- [x] create AuthCredential 
- [x] return auth сredential and identifier

## Acceptance Criteria

- Given that I’m using the PolygonID SDK
- When I create an identity using a seed phrase as input
- Then I can get the identifier and the authentication credential as a result

## Task Requirements

- [ ]  Follow Test Driven Development
- [ ]  Implement Unit Testing
- [ ]  Follow Clean Arquitecture
- [ ]  Add Documentation
