### ISSUE TITLE
[Mobile SDK] Credential Wallet - List

### ISSUE THREAD

**Issue by rauljareno** [iden3/polygonid-flutter-sdk#41]
## Acceptance Criteria

- Given that I’m using the PolygonID SDK
- When I get ask for the credentials stored in the SDK
- Then I can get the list of credentials as a result

## Task Requirements

- [ ]  Follow Test Driven Development
- [ ]  Implement Unit Testing
- [ ]  Follow Clean Arquitecture
- [ ]  Add Documentation

## Subtasks:
