### ISSUE TITLE
[Mobile SDK] Credential Wallet - Save

### ISSUE THREAD

**Issue by rauljareno** [iden3/polygonid-flutter-sdk#42]
## Acceptance Criteria

- Given that I’m using the PolygonID SDK
- When I want to store a credential in the SDK
- Then I can successfully store the credential as result

## Task Requirements

- [ ]  Follow Test Driven Development
- [ ]  Implement Unit Testing
- [ ]  Follow Clean Arquitecture
- [ ]  Add Documentation

## Subtasks:
