### ISSUE TITLE
[Mobile SDK] Credential Wallet - Find by query

### ISSUE THREAD

**Issue by rauljareno** [iden3/polygonid-flutter-sdk#43]
## Description

findByQuery ( query according to [[CRL](https://www.notion.so/Query-language-WIP-87f82c3077b442c7a01de9ed7547479c)]
    - [ ] parsing the query
    - [ ] Search by utilizing filters and building ‘query’ path

## Status
Need more information from Identity Team

## Acceptance Criteria

- Given that I’m using the PolygonID SDK
- When I want to search for credentials by query in the SDK
- Then I can successfully obtain the credentials that fulfill the requirements as result

## Task Requirements

- [ ]  Follow Test Driven Development
- [ ]  Implement Unit Testing
- [ ]  Follow Clean Arquitecture
- [ ]  Add Documentation

## Subtasks:
