### ISSUE TITLE
[Mobile SDK] Credential Wallet - Find by Id

### ISSUE THREAD

**Issue by rauljareno** [iden3/polygonid-flutter-sdk#44]
## Acceptance Criteria

- Given that I’m using the PolygonID SDK
- When I want to search for credentials by id in the SDK
- Then I can successfully obtain the credentials that fulfill the requirements as result

## Task Requirements

- [ ]  Follow Test Driven Development
- [ ]  Implement Unit Testing
- [ ]  Follow Clean Arquitecture
- [ ]  Add Documentation

## Subtasks:
